# Generated by Django 4.1.1 on 2022-11-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Placed', 'Placed'), ('Shipped', 'Shipped'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancelled_item', 'Cancelled_item'), ('return', 'return'), ('Refund Initiated', 'Refund Initiated')], default='New', max_length=150),
        ),
    ]
